---
title: "P8106-Midterm"
output: github_document
date: "2026-03-24"
---

```{r}
if (!dir.exists("figures")) dir.create("figures")
if (!dir.exists("tables")) dir.create("tables")
```


```{r}
library(ggplot2)
library(caret)
library(patchwork)
library(glmnet)
library(tidyverse)
library(corrplot)
library(mgcv)
library(earth)
library(randomForest)
library(xgboost)
library(gam)

set.seed(123)
```

```{r}
# load data
load("datA.RData")
datA

str(datA)
summary(datA)
```

```{r}
# check missing value
sum(is.na(datA))
```


## EDA

```{r}
# check y distribution
p <- ggplot(datA, aes(x = log_PFS)) +
  geom_histogram(bins = 30) +
  theme_minimal()

ggsave("figures/logPFS_hist.png", plot = p, width = 6, height = 4, dpi = 300)
```

```{r}
# numerical variables
# eda_numeric <- function(data, var, response = "log_PFS") {
eda_numeric <- function(data, var, response = "log_PFS", save_plot = TRUE, out_dir = "figures") {

  
  # Histogram
  p_hist <- ggplot(data, aes(x = .data[[var]])) +
    geom_histogram(fill = "lightblue", color = "white", bins = 30) +
    labs(title = paste("Histogram of", var), x = var, y = "Frequency") +
    theme_minimal()
  
  # Boxplot
  p_box <- ggplot(data, aes(y = .data[[var]])) +
    geom_boxplot(fill = "green4") +
    labs(title = paste("Boxplot of", var), y = var) +
    theme_minimal() +
    theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()) 
  
  # Scatter plot
  p_scatter <- ggplot(data, aes(x = .data[[var]], y = .data[[response]])) +
    geom_point(alpha = 0.3, color = "darkblue") +
    geom_smooth(method = "loess", color = "red") +
    labs(title = paste(var, "vs", response), x = var, y = response) +
    theme_minimal()
  
  combined_plot <- (p_hist | p_box) / p_scatter +
    plot_annotation(tag_levels = 'A')
  
  print(combined_plot)
  
  if (save_plot) {
    ggsave(
      filename = file.path(out_dir, paste0("EDA_numeric_", var, ".png")),
      plot = combined_plot,
      width = 10,
      height = 8,
      dpi = 300
    )
  }
}
```

```{r}
# categorical variables
eda_categorical <- function(data, var, response = "log_PFS", save_plot = TRUE, out_dir = "figures") {
# eda_categorical <- function(data, var, response = "log_PFS") {
  boxplot(data[[response]] ~ data[[var]],
          main = paste("Boxplot of", response, "by", var),
          xlab = var,
          ylab = response,
          col = "lightgreen")
  
  if (save_plot) {
    png(
      filename = file.path(out_dir, paste0("EDA_categorical_", var, ".png")),
      width = 900,
      height = 700,
      res = 120
    )
  }
  
  boxplot(data[[response]] ~ data[[var]],
          main = paste("Boxplot of", response, "by", var),
          xlab = var,
          ylab = response,
          col = "lightgreen")
  
  if (save_plot) dev.off()
}
```

```{r}
numeric_vars <- c("age", "bmi", "tumor_size", "lymph_nodes", "Ki67")
categorical_vars <- c("menopause", "race", "tumor_grade", "ER", "PR", 
                      "HER2", "stage", "surgery", "chemo", "hormonal_therapy")
```

```{r}
for (v in numeric_vars) {
  eda_numeric(datA, v)
}
```

```{r}
for (v in categorical_vars) {
  eda_categorical(datA, v)
}
```

## correlation
```{r}
numeric_data <- datA[, numeric_vars]
cor_matrix <- cor(numeric_data, use = "complete.obs")
cor_matrix 
```

```{r}
# png("figures/correlation_plot.png", width = 800, height = 600, res = 120)
# 
# corrplot(cor_matrix, method = "color", type = "upper",
#          addCoef.col = "black",  # show numbers
#          tl.col = "black", tl.srt = 45)
# 
# dev.off()


plot_corr <- function() {
  corrplot(cor_matrix, method = "color", type = "upper",
         addCoef.col = "black",  # show numbers
         tl.col = "black", tl.srt = 45)
}

plot_corr()

png("figures/correlation_plot.png", width = 800, height = 600, res = 120)
plot_corr()
invisible(dev.off())
```


## Model fitting

```{r}
# feature matrix
x <- model.matrix(log_PFS ~ . - id, data = datA)[, -1]
y <- datA$log_PFS
```

```{r}
# cross validation setup
ctrl <- trainControl(
  method = "repeatedcv",
  number = 10,
  repeats = 5
)
```

# linear regression
```{r}
lm_fit <- train(
  x, y,
  method = "lm",
  trControl = ctrl,
  preProcess = c("center", "scale")
)
```

# LASSO1
```{r}
lasso_fit <- train(
  x, y,
  method = "glmnet",
  trControl = ctrl,
  preProcess = c("center", "scale"),
  tuneGrid = expand.grid(
    alpha = 1,
    lambda = 10^seq(-3, 0, length = 30)
  )
)

lasso_fit$results
```

# LASSO2
```{r}
lasso2 <- train(
  log_PFS ~ 
      tumor_size + I(tumor_size^2) +
      lymph_nodes + I(lymph_nodes^2) +
      tumor_size:lymph_nodes +
      age +
      Ki67 + I(Ki67^2) +
      tumor_grade +
      ER + HER2 + hormonal_therapy,
  data = datA,
  method = "glmnet",
  tuneGrid = expand.grid(alpha = 1, lambda = 10^seq(-3, -1, length = 20)),
  trControl = ctrl
)
```

# LASSO3
```{r}
lasso3 <- train(
  log_PFS ~ 
      tumor_size +
      lymph_nodes +
      tumor_size:lymph_nodes +
      age +
      Ki67 +
      tumor_grade +
      ER + HER2 + hormonal_therapy,
  data = datA,
  method = "glmnet",
  tuneGrid = expand.grid(alpha = 1, lambda = 10^seq(-3, -1, length = 20)),
  trControl = ctrl
)
lasso3$results
```

# Elastic net
```{r}
enet_fit <- train(
  x, y,
  method = "glmnet",
  trControl = ctrl,
  preProcess = c("center", "scale"),
  tuneGrid = expand.grid(
    alpha = seq(0, 1, by = 0.1),
    lambda = 10^seq(-4, 1, length = 50)
  )
)
enet_fit$results
```

# GAM
```{r}
gam_fit <- train(
  x, y,
  method = "gamSpline",
  trControl = ctrl,
  preProcess = c("center", "scale"),
  tuneLength = 10
)
```

# MARS
```{r}
mars_fit <- train(
  x, y,
  method = "earth",
  trControl = ctrl,
  preProcess = c("center", "scale"),
  tuneGrid = expand.grid(
    degree = 1:3,
    nprune = seq(5, 50, by = 5)
  )
)
```


# Polynomial regression
```{r}
poly_fit <- train(
  log_PFS ~ 
                  tumor_size + I(tumor_size^2) +
                  log(lymph_nodes + 1) +
                  tumor_size:lymph_nodes +
                  age +
                  log(Ki67 + 1) +
                  tumor_grade +
                  ER + HER2 + hormonal_therapy,
                data = datA,
  method = "lm",
  trControl = ctrl
)
```

```{r}
library(gridExtra)
library(grid)

results <- resamples(list(
  Linear = lm_fit,
  Lasso1 = lasso_fit,
  Lasso2 = lasso2,
  Lasso3 = lasso3,
  ElasticNet = enet_fit,
  GAM = gam_fit,
  MARS = mars_fit,
  poly = poly_fit 
))

summary(results)
bwplot(results)
dotplot(results)

sum_res <- summary(results)
png("tables/resample_RMSE.png", width = 1200, height = 700)
grid.table(as.data.frame(sum_res$statistics$RMSE))
dev.off()

png("tables/resample_Rsquared.png", width = 1200, height = 700)
grid.table(as.data.frame(sum_res$statistics$Rsquared))
dev.off()

p_bw <- bwplot(results)
png("figures/bwplot_results.png", width = 1000, height = 700)
print(p_bw)
dev.off()

p_dot <- dotplot(results)
png("figures/dotplot_results.png", width = 1000, height = 700)
print(p_dot)
dev.off()
```

```{r}
model_list <- list(
  Lasso1 = lasso_fit,
  Lasso2 = lasso2,
  Lasso3 = lasso3,
  ElasticNet = enet_fit,
  GAM = gam_fit,
  MARS = mars_fit,
  poly = poly_fit
)

lapply(model_list, function(x) x$bestTune)

best_tune_df <- bind_rows(
  lapply(names(model_list), function(nm) {
    df <- as.data.frame(model_list[[nm]]$bestTune)
    df$Model <- nm
    df
  })
)


best_tune_df <- best_tune_df[, c("Model", setdiff(names(best_tune_df), "Model"))]
png("tables/best_tune_models.png", width = 1400, height = 700, res = 150)
grid.table(best_tune_df)
dev.off()
```


# Fit data B

```{r}
# load data
load("datB.RData")
datB

str(datB)
summary(datB)
```

```{r}
pred_B <- predict(gam_fit, newdata = datB)

postResample(pred = pred_B, obs = datB$log_PFS)
```
```{r}
pred_list <- lapply(model_list, function(m) {
  predict(m, newdata = datB)
})

results <- sapply(pred_list, function(pred) {
  postResample(pred = pred, obs = datB$log_PFS)
})

results <- t(results)

results[order(results[, "RMSE"]), ]
```


# 下面的不要了

```{r}
# feature matrix
# x <- model.matrix(log_PFS ~ . - id, data = datB)[, -1]
# y <- datB$log_PFS
```

```{r}
# cross validation setup
# ctrl <- trainControl(
#   method = "repeatedcv",
#   number = 10,
#   repeats = 5
# )
```

# linear regression
```{r}
# lm_fit <- train(
#   x, y,
#   method = "lm",
#   trControl = ctrl,
#   preProcess = c("center", "scale")
# )
```

# LASSO
```{r}
# lasso_fit <- train(
#   x, y,
#   method = "glmnet",
#   trControl = ctrl,
#   preProcess = c("center", "scale"),
#   tuneGrid = expand.grid(
#     alpha = 1,
#     lambda = 10^seq(-3, 0, length = 30)
#   )
# )
# 
# lasso_fit$results
```

# LASSO2
```{r}
# lasso2 <- train(
#   log_PFS ~ 
#       tumor_size + I(tumor_size^2) +
#       lymph_nodes + I(lymph_nodes^2) +
#       tumor_size:lymph_nodes +
#       age +
#       Ki67 + I(Ki67^2) +
#       tumor_grade +
#       ER + HER2 + hormonal_therapy,
#   data = datB,
#   method = "glmnet",
#   tuneGrid = expand.grid(alpha = 1, lambda = 10^seq(-3, -1, length = 20)),
#   trControl = ctrl
# )
```

# LASSO3
```{r}
# lasso3 <- train(
#   log_PFS ~ 
#       tumor_size +
#       lymph_nodes +
#       tumor_size:lymph_nodes +
#       age +
#       Ki67 +
#       tumor_grade +
#       ER + HER2 + hormonal_therapy,
#   data = datB,
#   method = "glmnet",
#   tuneGrid = expand.grid(alpha = 1, lambda = 10^seq(-3, -1, length = 20)),
#   trControl = ctrl
# )
```

# Elastic net
```{r}
# enet_fit <- train(
#   x, y,
#   method = "glmnet",
#   trControl = ctrl,
#   preProcess = c("center", "scale"),
#   tuneGrid = expand.grid(
#     alpha = seq(0, 1, by = 0.1),
#     lambda = 10^seq(-4, 1, length = 50)
#   )
# )
# enet_fit$results
```

# GAM
```{r}
# gam_fit <- train(
#   x, y,
#   method = "gamSpline",
#   trControl = ctrl,
#   preProcess = c("center", "scale"),
#   tuneLength = 10
# )
```

# MARS
```{r}
# mars_fit <- train(
#   x, y,
#   method = "earth",
#   trControl = ctrl,
#   preProcess = c("center", "scale"),
#   tuneGrid = expand.grid(
#     degree = 1:3,
#     nprune = seq(5, 50, by = 5)
#   )
# )
```

# Polynomial regression
```{r}
# poly_fit <- train(
#   log_PFS ~ 
#                   tumor_size + I(tumor_size^2) +
#                   log(lymph_nodes + 1) +
#                   tumor_size:lymph_nodes +
#                   age +
#                   log(Ki67 + 1) +
#                   tumor_grade +
#                   ER + HER2 + hormonal_therapy,
#                 data = datB,
#   method = "lm",
#   trControl = ctrl
)
```


```{r}
# results <- resamples(list(
#   Linear = lm_fit,
#   Lasso1 = lasso_fit,
#   Lasso2 = lasso2,
#   Lasso3 = lasso3,
#   ElasticNet = enet_fit,
#   GAM = gam_fit,
#   MARS = mars_fit,
#   poly = poly_fit 
# ))
# 
# summary(results)
# bwplot(results)
# dotplot(results)
```
